/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./src/components/ActionCard.vue')['default']
    BottomNavigation: typeof import('./src/components/BottomNavigation.vue')['default']
    CurrentPlayingBar: typeof import('./src/components/CurrentPlayingBar.vue')['default']
    ImportDialog: typeof import('./src/components/ImportDialog.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PlayerCard: typeof import('./src/components/PlayerCard.vue')['default']
    PlaylistActionItem: typeof import('./src/components/PlaylistActionItem.vue')['default']
    PlaylistActionList: typeof import('./src/components/PlaylistActionList.vue')['default']
    PlaylistCard: typeof import('./src/components/PlaylistCard.vue')['default']
    PlaylistQueue: typeof import('./src/components/PlaylistQueue.vue')['default']
    PlaylistSection: typeof import('./src/components/PlaylistSection.vue')['default']
    QuickActions: typeof import('./src/components/QuickActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchField: typeof import('./src/components/SearchField.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VAvatar: typeof import('vuetify/components')['VAvatar']
    VBottomNavigation: typeof import('vuetify/components')['VBottomNavigation']
    VBottomSheet: typeof import('vuetify/components')['VBottomSheet']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardSubtitle: typeof import('vuetify/components')['VCardSubtitle']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDialog: typeof import('vuetify/components')['VDialog']
    VDivider: typeof import('vuetify/components')['VDivider']
    VIcon: typeof import('vuetify/components')['VIcon']
    VImg: typeof import('vuetify/components')['VImg']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemContent: typeof import('vuetify/components')['VListItemContent']
    VListItemSubtitle: typeof import('vuetify/components')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VProgressLinear: typeof import('vuetify/components')['VProgressLinear']
    VRow: typeof import('vuetify/components')['VRow']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VTextField: typeof import('vuetify/components')['VTextField']
  }
}
